
# 3.2.2 Индексирование и вырезание

## Задание 1

Конечно, давайте создадим аналогичную задачу без использования изображения.

**Условие:**
Создайте целочисленный массив `ndarray` размера `(3,3)`. Представьте, что каждый элемент этого массива находится на черной позиции, как показано на следующей схеме:

```
B  W  B
W  B  W
B  W  B
```

Теперь, используя индексы элементов на черных позициях (B), выполните 4 выборки элементов согласно следующим выражениям:

1. Выборка элементов с индексами `(0, 0)`, `(1, 1)`, `(2, 2)`.
2. Выборка элементов с индексами `(0, 2)`, `(1, 1)`, `(2, 0)`.
3. Выборка элементов с индексами `(0, 1)`, `(1, 1)`, `(2, 1)`.
4. Выборка элементов с индексами `(1, 0)`, `(1, 1)`, `(1, 2)`.

Найдите максимальное значение в каждой из полученных выборок.

**Формат ответа:**
Кортеж чисел (например, `(3, 5, 2, 6)`).

**Решение:**

In [ ]:
import numpy as np

# Создаем целочисленный массив размера (3,3) с черными и белыми позициями
array = np.array([[1, 0, 1],
                  [0, 1, 0],
                  [1, 0, 1]])

# Создаем массив индексов черных позиций
black_indices = np.argwhere(array == 1)

# Печатаем массив с черными позициями
print("Массив с черными позициями:")
print(array)

# Выборка элементов по заданным индексам и нахождение максимального значения
result = (array[0,0], array[1,1], array[2,2]), (array[0,2], array[1,1], array[2,0]), \
         (array[0,1], array[1,1], array[2,1]), (array[1,0], array[1,1], array[1,2])

# Находим максимальное значение в каждой выборке
max_values = tuple([max(samples) for samples in result])

max_values

Массив с черными позициями:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


(1, 1, 1, 1)

## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```100``` элементов, принадлежащих отрезку ```[0,10]```. С помощью булевой индексации найдите все четные элементы в массиве. Найдите сумму полученных элементов. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)

**Оценка в баллах:** 3 балла

**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)
array = np.random.randint(0, 11, 100)
even_elements = array[array % 2 == 0]
sum_even_elements = np.sum(even_elements)

sum_even_elements

266

## Задание 3

**Условие:**
Создайте случайный целочисленный массив ndarray размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте подвыборку по всем строкам с нечетным индексом. Найдите сумму всех элементов в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```150```)

**Оценка в баллах:** 4 балла


**Решение:**

In [ ]:
import numpy as np

# Установим seed для воспроизводимости
np.random.seed(1000)

# Создание случайного массива размером (10, 10) с целыми числами от 0 до 10
arr = np.random.randint(0, 11, (10, 10))

# Выбор строк с нечетным индексом
sub_arr = arr[1::2]

# Нахождение суммы всех элементов в полученной матрице
result = np.sum(sub_arr)

print(result)


253
